//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Board
{
	public virtual MainTrack MainTrack
	{
		get;
		set;
	}

	public virtual Warehouse Warehouse
	{
		get;
		set;
	}

	public virtual IEnumerable<Switch> Switch
	{
		get;
		set;
	}

	public virtual Ship Ship
	{
		get;
		set;
	}

}

