//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MainTrack
{
	public virtual Minecart Contains
	{
		get;
		set;
	}

	public virtual MainTrack Next
	{
		get;
		set;
	}

	public virtual MainTrack Previous
	{
		get;
		set;
	}

	public virtual Minecart Minecart
	{
		get;
		set;
	}

	public virtual void IsEmty()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Place()
	{
		throw new System.NotImplementedException();
	}

}

