//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BaseTrack
{
	private object Content
	{
		get;
		set;
	}

	public virtual Minecart Content
	{
		get;
		set;
	}

	public virtual BaseTrack Next
	{
		get;
		set;
	}

	public virtual BaseTrack Previous
	{
		get;
		set;
	}

	public virtual bool IsEmpty()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Place()
	{
		throw new System.NotImplementedException();
	}

	public virtual Char ToChar()
	{
		throw new System.NotImplementedException();
	}

}

