//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Controller
{
	public virtual Board Board
	{
		get;
		set;
	}

	public virtual InputView InputView
	{
		get;
		set;
	}

	public virtual OutputView OutputView
	{
		get;
		set;
	}

	private void HandleGameInput(object string input)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Start()
	{
		throw new System.NotImplementedException();
	}

}

