//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Dock : BaseTrack
{
	public virtual Ship Ship
	{
		get;
		set;
	}

	public virtual Board Board
	{
		get;
		set;
	}

	public override void Place()
	{
		throw new System.NotImplementedException();
	}

	public override Char ToChar()
	{
		throw new System.NotImplementedException();
	}

}

