//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Ship
{
	public virtual int Cargo
	{
		get;
		set;
	}

	public virtual void Sail()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ToChar()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool IsDocked()
	{
		throw new System.NotImplementedException();
	}

	private void Reset()
	{
		throw new System.NotImplementedException();
	}

}

