//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Switch : BaseTrack
{
	private object Inactive
	{
		get;
		set;
	}

	public virtual BaseTrack Inactive
	{
		get;
		set;
	}

	public override void Place()
	{
		throw new System.NotImplementedException();
	}

	public Switch()
	{
	}

}

