//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConvergingSwitch : Switch
{
	public virtual bool IsDown{get;set;}
    public LinkedListNode<MainTrack> Link1 { get; set; }
    public LinkedListNode<MainTrack> Link2 { get; set; }

	public virtual MainTrack MainTrack{get;set;}

	public ConvergingSwitch()
	{
        IsDown = true;

	}

    public void Switch(){

    }

    public void addLink(LinkedListNode<MainTrack> link) {
        if (Link1 == null)
        {
            Link1 = link;
        }
        else if (Link2 == null) {
            Link2 = link;
        }
    }

    public override char ToChar()
    {
        if (Contains == null)
        {
            return 'C';
        }
        else
        {
            return Contains.ToChar();
        }
    }
}

