//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConvergingSwitch : Switch
{

	public virtual MainTrack MainTrack{get;set;}

	public ConvergingSwitch()
	{
        IsDown = true;

	}

    public void Switch(){

    }
    public override bool Move(LinkedList<MainTrack> route, List<MainTrack> usedTracks)
    {
        return true;

    }
        


    public override char ToChar()
    {
        if (Contains == null)
        {
            if (!IsDown)
            {
                return '└';
            }
            return '┌';
        }
        else
        {
            return Contains.ToChar();
        }
    }
}

