//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConvergingSwitch : Switch
{



	public ConvergingSwitch()
	{
        IsDown = true;

	}

    public void Switch(){

    }
    public override bool Move(LinkedList<MainTrack> route, List<MainTrack> usedTracks)
    {
        

        if (route.Find(this) == null)
        {
            return false;
        }
      
     
        if(!IsDown){
            
            if (route.First.Equals(Link1.List.First))
            {
                
                route.Find(this).Value.Place(route.Find(this).Previous.Value.Contains);
                route.Find(this).Previous.Value.Contains = null;
                usedTracks.Remove(route.Find(this).Previous.Value);
                usedTracks.Add(route.Find(this).Value);
                return true;
            }
            else
            {
                return false;
            }
      
        }
        else if(IsDown){

            if (route.First.Equals(Link2.List.First))
            {
                route.Find(this).Value.Place(route.Find(this).Previous.Value.Contains);
                route.Find(this).Previous.Value.Contains = null;
                usedTracks.Remove(route.Find(this).Previous.Value);
                usedTracks.Add(route.Find(this).Value);
                return true;
            }
            else
            {
                return false;
            }
        }
        return false;
    }
        


    public override char ToChar()
    {
        if (Contains == null)
        {
            if (!IsDown)
            {
                return '└';
            }
            return '┌';
        }
        else
        {
            return Contains.ToChar();
        }
    }
}

