//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DevergingSwitch : Switch
{


	public DevergingSwitch()
	{
        IsDown = false;
	}



    public override char ToChar()
    {
        if (Contains == null)
        {
            return 'I';
        }
        else
        {
            return Contains.ToChar();
        }
    }
}

