//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MainTrack
{
    public virtual Minecart Contains { get; set; }

    public bool GameOver;

    public MainTrack()
    {
        GameOver = false;
    }

    public Boolean IsEmty()
    {
        if (Contains == null)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    public bool Place(Minecart cart)
    {
        if (IsEmty())
        {
            Contains = cart;
            return true;
        }

        return false;
    }
    public virtual char ToChar()
    {
        if (Contains == null)
        {
            return '#';
        }
        else
        {
            return Contains.ToChar();
        }
    }

    public virtual bool Move(LinkedList<MainTrack> route, List<MainTrack> usedTracks)
    {

        
            if (route.Find(this) == null)
            {
                return false;
            }
            route.Find(this).Value.Place(route.Find(this).Previous.Value.Contains);
            route.Find(this).Previous.Value.Contains = null;
            usedTracks.Remove(route.Find(this).Previous.Value);
            usedTracks.Add(route.Find(this).Value);
            return true;
        }
        
    

}

