//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SafeTrack : BaseTrack
{
	public override bool Place(Minecart mc)
	{
		if (Content == null)
		{
			Content = mc;
			Previous.Content = null;
			return true;
		}

		if (Previous.ToChar(true) == '#')
			throw new JeMoederException();

		return false;
	}

	public override Char ToChar(bool rawChar)
	{
		if (!rawChar)
		{
			if (IsEmpty())
				return 'L';

			return Content.ToChar();
		}

		return 'L';
	}

	public Char ToRawChar()
	{
		return 'L';
	}

}

